# Generated by Django 3.2.16 on 2022-12-30 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20221229_2353'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='author',
            field=models.CharField(default='名無しさん', max_length=200),
            preserve_default=False,
        ),
    ]
